### PR TITLE
fix(frontend): fix select_trait_candidate

### LINKED ISSUE #461: Extraction fails with `select_trait_candidate`
A bunch of functions in Bertie fail with `select_trait_candidate`. They all seem to use `collect`.

Here are tests for them.
https://github.com/hacspec/hax/pull/new/franziskus/select_trait_candidate

### PR DESCRIPTION
**Pull request by W95Psp**
Fixes #461 and #476

### CODE REVIEW

**Review by franziskuskiefer — CHANGES_REQUESTED** [review]
This makes hax crash. For example

```
Fatal error: exception Failure("impl_expr_atom: Todo ImplExprAtom::Todo(see https://github.com/hacspec/hax/issues/381) ImplSourceClosureData(closure_def_id=DefId(0:673 ~ bertie[019b]::tls13utils::{impl#3}::declassify::{closure#0}), substs=[i16, extern \"rust-call\" fn((&u8,)) -> u8, ()], nested=[Obligation(predicate=Binder(ClosureKind(DefId(0:673 ~ bertie[019b]::tls13utils::{impl#3}::declassify::{closure#0}), [i16, extern \"rust-call\" fn((&u8,)) -> u8, ()], FnMut), []), depth=1)])\n\nBinder(\n    <[closure@src/tls13utils.rs:202:27: 202:30] as std::ops::FnMut<(&u8,)>>,\n    [],\n)")
Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
Called from Hax_engine__Import_thir.Make.c_impl_expr in file "lib/import_thir.ml", line 906, characters 15-44
```

**Comment by W95Psp** [comment]
Yes, I noticed it's producing new bugs :sweat_smile: 
But that is fine: those are just new cases I need to take care of, I see what is the problem, that's just some small legitimate changes to do :)

**Comment by franziskuskiefer** [comment]
you force pushed again 😔

**Review by franziskuskiefer — APPROVED** [review]
Lets get this in

**Comment by W95Psp** [comment]
Great, thank you :smiley:

**Pull request merged**
