### PR TITLE
Exporter get variant information works on unions

### LINKED ISSUE #997: Exporter: handle union construction
We currently fail when constructing unions, e.g.:
```rust
union Test {
    a: i16,
    b: u32,
}

fn f() -> Test {
    Test {b : 123}
}
```
[Open this code snippet in the playground](https://hax-playground.cryspen.com/#json/a385e57479/gist=39663f409696468187df64d8321a940a)

The fix is trivial: remove the assert from `get_variant_information`, which works fine on unions.
Before doing that, I want to change a bit `VariantInformations`, which is not very well designed (the `*_is_*` fields are annoying).

This is required to run hax on the `aes` crate of https://github.com/RustCrypto/block-ciphers

### PR DESCRIPTION
**Pull request by W95Psp**
Fixes #997.
I have a meeting but then I'll push related changes in Charon.

### CODE REVIEW

**Comment by Nadrieril** [comment]
I don't expect this requires charon changes, the CI is only broken because I haven't yet fixed charon after last PR. That's just waiting on my CI: https://github.com/AeneasVerif/charon/pull/418.

**Comment by W95Psp** [comment]
That'll break charon here: https://github.com/AeneasVerif/charon/blob/75ebb6fccdf208b92343395cd05378790d0496c3/charon/src/bin/charon-driver/translate/translate_constants.rs#L87-L98

**Comment by W95Psp** [comment]
This is green on Charon :smiley: (https://github.com/AeneasVerif/charon/actions/runs/11329658628/job/31506938774)

**Comment by W95Psp** [comment]
@Nadrieril I tagged you as a reviewer just in case you have opinions, but feel free to ignore :smiley:

**Review by Nadrieril — APPROVED** [review]
LGTM, this is a nice improvement :)

**Review by maximebuyse — APPROVED** [review]

**Pull request merged**
