### PR TITLE
Fix bug with recursive bundles depending on items from original modules.

### PR DESCRIPTION
**Pull request by maximebuyse**
Fixes a bug found while investigating #995 . More generally this fixes many problems in the bundling of cyclic dependencies

### CODE REVIEW

**Comment by maximebuyse** [comment]
As described [here](https://github.com/hacspec/hax/issues/995#issuecomment-2413253296) the problem is more complex than I usually thought if one wants to minimize the amount of bundled items. So this PR implements a conservative approach (that is much more simple than what we did before): when there is a cycle at the module level, it bundles together in a new module everything the content of all the modules in the cycle. https://github.com/hacspec/hax/issues/1005 will track whether this is practical enough and if we should find an algorithm to minimize bundles.

**Review by W95Psp — APPROVED** [review]
LGTM, thanks!

**Comment by W95Psp** [comment]
Looks like tests snapshot are not up to date? :thinking:

**Comment by maximebuyse** [comment]
> Looks like tests snapshot are not up to date? 🤔

Yes, noticed that too. I am looking into it.

**Pull request merged**
