### PR TITLE
Update rustc

### PR DESCRIPTION
**Pull request by Nadrieril**
This pushes the rustc pin two months forward.

Something weird to note: in the first commit, a bunch of std functions gain a new invisible const generics argument. A later commit reverts this. But this happens again for nightlies in December. I stopped mid-November to give me time to investigate what's happening there.

### CODE REVIEW

**Comment by Nadrieril** [comment]
I investigated, the weirdness has to do with the `const_trait` attribute. E.g. https://github.com/rust-lang/rust/pull/118661 adds this attribute to `PartialEq`, and the consequence in hax/charon is that the trait seems to have an extra `const host: bool` generic argument. This attribute is still here today so we'll have to handle it somehow.

**Comment by Nadrieril** [comment]
The corresponding charon PR is ready (https://github.com/AeneasVerif/charon/pull/254). This can be merged.

**Review by W95Psp — APPROVED** [review]
Thank you and sorry for the long response time. That looks good to me, let's merge that ASAP!

**Comment by Nadrieril** [comment]
:tada: thank you!

**Pull request merged**
