### PR TITLE
Machine int constructors and conversions

### PR DESCRIPTION
**Pull request by karthikbhargavan**
This PR adds some functions to convert integers and F* integers to and from Rust integers.
For the most part these functions are trivial, but defining these functions makes it easier to transition code towards a future library that uses refined integers to represent machine integers (see `experiment-refined-ints`). 

This branch has been tested with libcrux branch `experiment-refined-ints`.

### CODE REVIEW

**Review by W95Psp — APPROVED** [review]
LGTM, thanks!

**Comment by W95Psp** [comment]
Ah, that seems to break tests though :thinking:

**Comment by karthikbhargavan** [comment]
@Nadrieril Could you help me debug the charon job failure on CI.
I didn't touch anything in the frontend. Maybe it is a Cargo.lock or flake.nix thing?

**Comment by Nadrieril** [comment]
Looked into it, turns out https://github.com/hacspec/hax/pull/1039 was merged that adds a field without me noticing, I'll fix that asap.

**Comment by karthikbhargavan** [comment]
Thank you!

**Pull request merged**
