### PR TITLE
fix(engine/importer): use correct field to import concrete implexprs

### LINKED ISSUE #834: Engine: `Concrete` `ImplExpr`s are not imported correctly
Consider this example:
```rust
trait Foo {
    fn do_thing(self: &Self) -> u64;
}

struct Bar {
    n: u64,
}

impl Foo for Bar {
    fn do_thing(self: &Self) -> u64 {
        self.n
    }
}

fn call_foo<F: Foo>(foo: &F) -> u64 {
    foo.do_thing()
}

fn use_bar() -> u64 {
    let b = Bar { n: 42 };
    call_foo(&b)
}
```

One of the trait bounds in the call to `call_foo` in the function `use_bar` is the fact that `Bar` implements `Foo`.

This information is exported as an `ImplExpr::Concrete`. The exported json looks something like this:
```json
{
  "trait": {
    "def_id": {
      "krate": "scratch",
      "path": [
        {
          "data": {
            "TypeNs": "Foo"
          },
          "disambiguator": 0
        }
      ],
      "index": [
        0,
        3
      ]
    },
    "generic_args": [
      {
        "Type": {
          "Adt": {
            "generic_args": [],
            "trait_refs": [],
            "def_id": {
              "krate": "scratch",
              "path": [
                {
                  "data": {
                    "TypeNs": "Bar"
                  },
                  "disambiguator": 0
                }
              ],
              "index": [
                0,
                5
              ]
            }
          }
        }
      }
    ]
  },
  "impl": {
    "Concrete": {
      "id": {
        "krate": "scratch",
        "path": [
          {
            "data": "Impl",
            "disambiguator": 0
          }
        ],
        "index": [
          0,
          7
        ]
      },
      "generics": []
    }
  },
  "args": []
}
```

The information about what type was used to implement what trait is stored in the `trait` field, whereas the `impl` field stores some useless marker.

The importer incorrectly imports the `impl` field as the final trait goal. Resulting in a junk `impl_expr` like this:
```json
[
  "Concrete",
  {
    "trait": {
      "def_id": {
        "krate": "scratch",
        "path": [
          {
            "data": [
              "Impl"
            ],
            "disambiguator": 0
          }
        ]
      },
      "kind": [
        "Impl"
      ]
    },
    "args": []
  }
]
```

### PR DESCRIPTION
**Pull request by paulmure**
Close #834.

@W95Psp some of the existing insta tests are failing and I'm not knowledgeable enough about them to see if they need to be updated.

### CODE REVIEW

**Comment by W95Psp** [comment]
Hi, thanks for your PR! Sorry for the delay, the week is quite busy... will try to look into those tests tomorrow!

**Review by W95Psp — APPROVED** [review]
Sorry for the delay... LGTM.

**Comment by W95Psp** [comment]
(forgot to push, doing that in a minute)

**Comment by W95Psp** [comment]
Ok, I'm in a rush and so I rushed the review as well... I wanted to merge too fast, and actually I think there is a problem with the PR. Let me comment on the issue.

**Comment by paulmure** [comment]
@W95Psp
As discussed in the [issue](https://github.com/hacspec/hax/issues/834#issuecomment-2324987173), I'm trying to import the trait goal alongside the information stored in `ImplExprAtom`.

However, this seems to break the uses of `ppx_inline` in many of the modules in `lib/phases`. I guess it's caused by incorrect inlining of the code in `subtype.ml`. And I'm not sure how to fix this.

Any suggestions would be greatly appreciated!

**Comment by paulmure** [comment]
> @W95Psp As discussed in the [issue](https://github.com/hacspec/hax/issues/834#issuecomment-2324987173), I'm trying to import the trait goal alongside the information stored in `ImplExprAtom`.
> 
> However, this seems to break the uses of `ppx_inline` in many of the modules in `lib/phases`. I guess it's caused by incorrect inlining of the code in `subtype.ml`. And I'm not sure how to fix this.
> 
> Any suggestions would be greatly appreciated!

Forget what I said here, I think I just needed to run `dune clean` before building.

**Comment by paulmure** [comment]
After some back and forth, I decided to only import the trait goal for the `concrete` case for now.

I'm not sure if it's actually needed for the other cases. If such a need arises in the future, we can reconsider how to import this information again.

All tests should pass now. The only change is that the traits test for f* added a line of implicit dependency.

**Comment by W95Psp** [comment]
Hi @paulmure, I'm reviewing this PR this morning, and I think I did something similar recently... https://github.com/hacspec/hax/pull/827
Sorry for the duplicate work... (the last month has been pretty work intensive toward a verification project...)

Wdyt, shall we close this one or is it still needed?

**Comment by paulmure** [comment]
That looks like the information we need. Thank you!

**Pull request closed without merging**
