### PR TITLE
Translate additional unsafe MIR operations

### PR DESCRIPTION
**Pull request by Nadrieril**

### CODE REVIEW

**Comment by franziskuskiefer** [comment]
Is the Charon CI failure expected?
I'll try to have a look later. @maximebuyse can you give this a pass too?

**Comment by Nadrieril** [comment]
The Charon failure is expected, I've made sure this PR doesn't break Charon myself

**Comment by maximebuyse** [comment]
> Is the Charon CI failure expected? I'll try to have a look later. @maximebuyse can you give this a pass too?

Looks good to me

**Review by franziskuskiefer — COMMENTED** [review]
~~The build fails for me with~~

Scratch that, looks like cargo was in a bad place. I haven't seen that before ... an interesting one.

**Review by franziskuskiefer — APPROVED** [review]
:shipit:

**Comment by Nadrieril** [comment]
Ty!

**Pull request merged**
