### PR TITLE
Skip generated impls using `Erased` attribute.

### LINKED ISSUE #1070: Cyclic dependency introduced by bundling with `let open`
```rust
pub mod a {
    #[derive(Debug)]
    pub struct S {}
    pub struct Sa(super::b::Sb);
    impl std::fmt::Debug for Sa {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            write!(f, "{:?}", self.0)
        }
    }

}

pub mod b {
    pub struct Sb(super::a::S);
    impl std::fmt::Debug for Sb {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            write!(f, "{:?}", self.0)
        }
    }
}
```
[Open this code snippet in the playground](https://hax-playground.cryspen.com/#fstar/001a27e207/gist=5c43e496c5fdf2dd5a8f47540b2ba269)

In the situation above, the recursive bundle contains a `let open` for one of the original modules creating a cycle.

### PR DESCRIPTION
**Pull request by maximebuyse**
Fixes #1070 

Instead of just skipping generated impls, this adds the `Erased` attribute to them so that the body is dropped but they still exist in the engine. This allows for them to be moved by bundling thus removing the spurious `let open`.

### CODE REVIEW

**Comment by maximebuyse** [comment]
Two comments here:
- the `skip` attribute seems to have been removed so maybe we can remove the corresponding logic in `import_thir`?
- there is a coq test that fails because of this (it generates a type class instance with dummy methods), maybe this means we should also implement the `Erased` attribute in the other backends.

**Comment by maximebuyse** [comment]
> Two comments here:
> 
>     * the `skip` attribute seems to have been removed so maybe we can remove the corresponding logic in `import_thir`?
> 
>     * there is a coq test that fails because of this (it generates a type class instance with dummy methods), maybe this means we should also implement the `Erased` attribute in the other backends.

For coq, I added a quick fix: it filters out trait impls that have the `Erased` attribute. I opened https://github.com/hacspec/hax/issues/1185 to add full support for `Erased` in the coq backend.

**Comment by maximebuyse** [comment]
> Two comments here:
> 
>     * the `skip` attribute seems to have been removed so maybe we can remove the corresponding logic in `import_thir`?
> 
>     * there is a coq test that fails because of this (it generates a type class instance with dummy methods), maybe this means we should also implement the `Erased` attribute in the other backends.

For `skip` we discussed it and it is indeed unused so I removed the logic. @W95Psp You can finish your review, I am done with my changes.

**Review by W95Psp — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
