### PR TITLE
Update to OCaml 5

### PR DESCRIPTION
**Pull request by W95Psp**
This PR updates the engine to OCaml 5

### CODE REVIEW

**Comment by franziskuskiefer** [comment]
Do we really want to do this when all our other tools don't? I'm of course all for updating, but I want to avoid incompatibilities.

**Comment by W95Psp** [comment]
Mmh, I was not thinking about that indeed.
But the engine of hax is not used as an OCaml library from any other projects, and it doesn't consume any other projects as an OCaml library.
So, since the projects compose only at the binary level, I think there won't be any incompatibilities.
Does that make sense or I'm missing a source of incompatibility?

**Review by franziskuskiefer — APPROVED** [review]
Ok, let's try it and see what happens.

Where's that Rust change coming from? Looks like formatting?

**Comment by W95Psp** [comment]
Yes, the Rust change is just about formatting. I think that's something rustfmt used not to format or something like that.

**Pull request merged**
