### PR TITLE
Revert "Normalize outside the binder"

### LINKED ISSUE #974: Regression in trait resolution
I have the following frontend error:
```
thread 'rustc' panicked at compiler/rustc_trait_selection/src/traits/normalize.rs:151:9:
Normalizing support::data_source::DataSource<'^1_0.Named(DefId(0:1727 ~ sandwich[df1c]::tunnel::tls::support::configuration_read_certificate::'_), "'_")> without wrapping in a `Binder`
```

The bug is a regression from https://github.com/hacspec/hax/pull/906 (extraction works with the commit before merging this). I tried to minimize but couldn't.
Here is the trace:
```
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms TRACE Enters sinto (rustc_middle::ty::PolyTraitRef<'tcx>)
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐impl_expr owner_id=DefId(0:274 ~ sandwich[df1c]::implementation::openssl3_impl::tunnel::context::{impl#4}::fill_certificate_trust_store), tref=Binder { value: <(pb_api::ASN1EncodingFormat, support::data_source::DataSource<'aaa>) as std::marker::Sized>, bound_vars: [] }
thread 'rustc' panicked at compiler/rustc_trait_selection/src/traits/normalize.rs:151:9:
Normalizing support::data_source::DataSource<'^1_0.Named(DefId(0:810 ~ sandwich[df1c]::tunnel::tls::support::configuration_read_certificate::'aaa), "'aaa")> without wrapping in a `Binder`
```

### PR DESCRIPTION
**Pull request by W95Psp**
This reverts commit f8035a79a94d7a00074fc3b134aa19e5d5c085b3.

Fixes #974.

cc @nadrieril

### CODE REVIEW

**Review by maximebuyse — APPROVED** [review]

**Comment by W95Psp** [comment]
btw, the change looks like identity to me, I don't get it, but I'm tired :man_shrugging:

**Comment by W95Psp** [comment]
@maximebuyse have you tried the PR on sandwich? This fixes my reproducer, not sure it fixes the original thing (I am not sure how to reproduce actually, in your issue there is no step for reproducing)

**Comment by maximebuyse** [comment]
> @maximebuyse have you tried the PR on sandwich? This fixes my reproducer, not sure it fixes the original thing (I am not sure how to reproduce actually, in your issue there is no step for reproducing)

@W95Psp Just tried and it fixes the original problem

**Comment by W95Psp** [comment]
Great, thanks! :relieved:

**Comment by Nadrieril** [comment]
That commit was there to fix another problem however

**Comment by Nadrieril** [comment]
And I just opened https://github.com/hacspec/hax/pull/977 with other improvements. Please let me fix things correctly

**Comment by Nadrieril** [comment]
As you can see from the charon failures, this PR is not a proper fix, it creates many other issues

**Comment by W95Psp** [comment]
Sorry for that, was done in a hurry. Let's close in favor of your PR!

**Pull request closed without merging**
